trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerRegistryServiceConnection: 'AcrDockerConnection'
  imageRepository: 'tech-challenge-contact'
  containerRegistry: 'postech.azurecr.io'
  dockerfilePath: 'Dockerfile'
  tag: '$(Build.BuildId)'
  imageToDeploy: '$(containerRegistry)/$(imageRepository):$(tag)'

stages:
  - stage: 'Development'
    jobs:
    - job: 'BuildAndPushImage'
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      # Setup Docker Buildx
      - script: |
          echo "Setting up Docker Buildx"
          docker run --rm --privileged tonistiigi/binfmt --install all
          docker buildx create --name mybuilder --use
          docker buildx inspect --bootstrap
        displayName: 'Set up Docker Buildx'

      # Login to ACR
      - task: Docker@2
        displayName: 'Login to ACR'
        inputs:
          containerRegistry: '$(dockerRegistryServiceConnection)'
          command: 'login'

      # Build and Push Docker image
      - task: Docker@2
        displayName: 'Build and Push Docker Image'
        inputs:
          containerRegistry: '$(dockerRegistryServiceConnection)'
          repository: '$(imageRepository)'
          command: 'buildAndPush'
          dockerfile: '$(dockerfilePath)'
          tags: |
            $(tag)
          buildContext: '.'

      # Debugging Step: Echo the image details
      - script: |
          echo "Image: $(imageToDeploy)"
        displayName: 'Echo Image Details'

    - job: 'DeployToAzure'
      dependsOn: 'BuildAndPushImage'
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      # Deploy to Azure Container Apps using Azure CLI
      - task: AzureContainerApps@1
        displayName: 'Deployment Azure Container Apps'
        inputs:
          azureSubscription: 'Pago pelo Uso(b4b453d5-839d-496b-a890-bafff37c5d56)'
          acrName: 'postech'
          imageToDeploy: '$(imageToDeploy)'
          containerAppName: 'postech-fiap'
          resourceGroup: 'postech'
          targetPort: '8080'

  - stage: 'Staging'
    displayName: 'Staging'
    jobs:
    - job: 'EchoMessage'
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      # Echo Message
      - script: |
          echo "This is the Staging stage."
        displayName: 'Echo Staging Message'